import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
    title: "POLES",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr" suppressHydrationWarning>
            <body className={cn("min-h-screen bg-background font-sans antialiased")}>
                <Navbar />
                {children}
                <section className="mt-24 bg-[#1E233F] py-24">

                </section>
            </body>
        </html>
    );
}
