import type { Metadata } from "next";
import "../globals.css";
import { cn } from "@/lib/utils";
import GlobalContextProvider from "@/context/globalcontext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr" suppressHydrationWarning>
            <GlobalContextProvider>
                <body className={cn("min-h-screen bg-background font-sans antialiased")}>{children}</body>
            </GlobalContextProvider>
        </html>
    );
}
